# Generated by Django 3.1.2 on 2020-11-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201123_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo6',
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo1',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
