# Generated by Django 3.1.2 on 2020-11-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('realty_company', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
    ]
